Fiz umas melhorias
Izurii/modem-vivo-avancado pull request #1
Opened 2024-06-17 00:32 UTC by autergame

2024-06-17 01:03 UTC, Izurii commented
Irei dar uma olhadinha depois!

2024-06-22 23:44 UTC, Izurii requested changes
Pequenos comentários, coisas bestas. Mas de resto, tá top demais :D

2024-06-22 23:44 UTC, Izurii commented on .gitignore
> +package-lock.json
Retirar os lock do gitignore. Em caso de discordância, gostaria de entender o porquê deveriamos deixar eles aí.

2024-06-22 23:44 UTC, Izurii commented on yarn.lock
Perdão, mas se o projeto foi iniciado utilizando Yarn como o gerenciador de pacotes/dependências, por que trocar pelo NPM?

2024-06-23 00:28 UTC, autergame commented on yarn.lock
Acredito que o npm seja mais prático para usuários que só querem usar, por ele já vir junto com o nodejs.

2024-06-23 00:33 UTC, autergame commented on .gitignore
> +package-lock.json
Adicionei o package-lock, tinha removido por costume.

2024-06-27 01:13 UTC, Izurii approved these changes

2024-06-27 01:14 UTC, merged